/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { IconName, } from "./components/varaus-icon/Icons";
import { Changed, } from "./components/varaus-form-field/varaus-form-field";
import { SignInAction, } from "./components/varaus-sign-in-form/varaus-sign-in-form";
export namespace Components {
    interface VarausButton {
        "disabled": boolean;
        "icon"?: IconName;
        "type": "submit" | "button" | "reset";
    }
    interface VarausFormField {
        "disabled": boolean;
        "icon"?: IconName;
        "label": string;
        "name": string;
        "placeholder": string;
        "type": string;
        "validationError": any;
        "value": string;
    }
    interface VarausIcon {
        "icon": IconName;
    }
    interface VarausSignInForm {
        "error": string;
        "success": string;
    }
}
declare global {
    interface HTMLVarausButtonElement extends Components.VarausButton, HTMLStencilElement {
    }
    var HTMLVarausButtonElement: {
        prototype: HTMLVarausButtonElement;
        new (): HTMLVarausButtonElement;
    };
    interface HTMLVarausFormFieldElement extends Components.VarausFormField, HTMLStencilElement {
    }
    var HTMLVarausFormFieldElement: {
        prototype: HTMLVarausFormFieldElement;
        new (): HTMLVarausFormFieldElement;
    };
    interface HTMLVarausIconElement extends Components.VarausIcon, HTMLStencilElement {
    }
    var HTMLVarausIconElement: {
        prototype: HTMLVarausIconElement;
        new (): HTMLVarausIconElement;
    };
    interface HTMLVarausSignInFormElement extends Components.VarausSignInForm, HTMLStencilElement {
    }
    var HTMLVarausSignInFormElement: {
        prototype: HTMLVarausSignInFormElement;
        new (): HTMLVarausSignInFormElement;
    };
    interface HTMLElementTagNameMap {
        "varaus-button": HTMLVarausButtonElement;
        "varaus-form-field": HTMLVarausFormFieldElement;
        "varaus-icon": HTMLVarausIconElement;
        "varaus-sign-in-form": HTMLVarausSignInFormElement;
    }
}
declare namespace LocalJSX {
    interface VarausButton {
        "disabled"?: boolean;
        "icon"?: IconName;
        "type"?: "submit" | "button" | "reset";
    }
    interface VarausFormField {
        "disabled"?: boolean;
        "icon"?: IconName;
        "label"?: string;
        "name"?: string;
        "onChanged"?: (event: CustomEvent<Changed>) => void;
        "placeholder"?: string;
        "type"?: string;
        "validationError"?: any;
        "value"?: string;
    }
    interface VarausIcon {
        "icon"?: IconName;
    }
    interface VarausSignInForm {
        "error"?: string;
        "onSignedin"?: (event: CustomEvent<SignInAction>) => void;
        "success"?: string;
    }
    interface IntrinsicElements {
        "varaus-button": VarausButton;
        "varaus-form-field": VarausFormField;
        "varaus-icon": VarausIcon;
        "varaus-sign-in-form": VarausSignInForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "varaus-button": LocalJSX.VarausButton & JSXBase.HTMLAttributes<HTMLVarausButtonElement>;
            "varaus-form-field": LocalJSX.VarausFormField & JSXBase.HTMLAttributes<HTMLVarausFormFieldElement>;
            "varaus-icon": LocalJSX.VarausIcon & JSXBase.HTMLAttributes<HTMLVarausIconElement>;
            "varaus-sign-in-form": LocalJSX.VarausSignInForm & JSXBase.HTMLAttributes<HTMLVarausSignInFormElement>;
        }
    }
}
